
CONTRACT_META="SANDBOX.KATRIN.CONTRACT_DATA"
P4_TS = "SANDBOX.KATRIN.P4_METERREADING_WINTER"
P4_TS = "SANDBOX.KATRIN.P4_METERREADING_SUMMER"

# big bois who are slow
P4_TS_OLD = "SANDBOX.KATRIN.ACTIVE_P4_READING"
CONTRACT_META_OLD="SSANDBOX.KATRIN.ACTIVE_CONTRACT_DATA"